DATABASE CONNECTION:
  DB HOST: 'localhost'
  DB NAME: 'pdm_release3'
  DB USERNAME: 'ilmaruduste'
  DB PASSWORD: 'banaan'
  DB PORT: '5432'

INPUT DATA:
  DATA SCHEMAS: ['ee_lab_results', 'ee_lab_results_copy']            # The first schema here is the one the other schemas are compared to. NB! There should be as many Data Schemas as corresponding types!
  CORRESPONDING TYPES: ['100% data', 'COPY 100% data']  # Type of sample/compression on data. E.g. '5% data' or '100% PIPE1 data'
  TABLE NAMES: ['tourism_dom_lau_m', 'tourism_inb_lau_d']
  INDICATORS: ['unique_visitor_cnt', 'trip_present_cnt', 'stay_present_cnt', 'trip_first_stay_cnt']
  DATA SOURCE: 'DomesticInbound' # Options 'DomesticInbound' and 'Outbound'
  JOIN CATEGORIES: ['lau_id', 'lau_level','period']
  FILTER NAME: 'lau_level' 
  FILTER VALUES: [1]

OUTPUT DATA:
  FOLDER: './output'
  FILENAME: 'ee_lab_copy_comparison.csv'
  TYPE: ['wide', 'long']                  # Long or wide or both

